### PR TITLE
[*] decrease `etcd_leader_checker.Config.DialKeepAliveTime` to 5sec

### LINKED ISSUE #179: Cannot assign address
Hello all,
We're having an issue when starting vip-manager on a CentOS 7 box where it can't assign the ip address to the interface eth0.
Here are the output of the command:

[root@bdgerr00 default]# /home2/postgres/ha-patroni/bin/vip-manager --config /home2/postgres/ha-patroni/conf/vip-manager.yml
2023/11/08 16:06:34 Using config from file: /home2/postgres/ha-patroni/conf/vip-manager.yml
2023/11/08 16:06:34 This is the config that will be used:
	config : /home2/postgres/ha-patroni/conf/vip-manager.yml
	dcs-endpoints : [https://127.0.0.1:22379 https://bdgerr00:22379 https://bdgerr01:22379 https://aplgerr00:22379]
	dcs-type : etcd
	etcd-ca-file : /home2/postgres/ha-patroni/certs/rootCA.crt
	etcd-cert-file : /home2/postgres/ha-patroni/certs/node.crt
	etcd-key-file : /home2/postgres/ha-patroni/certs/node.key
	etcd-password : *****
	etcd-user : root
	hosting-type : basic
	hostingtype : basic
	interface : eth0
	interval : 1000
	ip : 10.200.95.3
	manager-type : basic
	netmask : 24
	retry-after : 250
	retry-num : 2
	trigger-key : /service/digitro/leader
	trigger-value : bdgerr00
	verbose : true
	version : false
2023/11/08 16:06:34 IP address 10.200.95.3/24 state is true, desired false
2023/11/08 16:06:34 Removing address 10.200.95.3/24 on eth0
2023/11/08 16:06:34 Got error RTNETLINK answers: Cannot assign requested address
2023/11/08 16:06:34 Error while acquiring virtual ip for this machine
2023/11/08 16:06:44 IP address 10.200.95.3/24 state is true, desired true

Doing the command ip manually it works.

[root@bdgerr00 default]# ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 46:23:9e:48:c5:5e brd ff:ff:ff:ff:ff:ff
    inet 10.200.95.36/24 brd 10.200.95.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::4423:9eff:fe48:c55e/64 scope link 
       valid_lft forever preferred_lft forever
[root@bdgerr00 default]# ip addr add 10.200.95.3/24 dev eth0 
[root@bdgerr00 default]# ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 46:23:9e:48:c5:5e brd ff:ff:ff:ff:ff:ff
    inet 10.200.95.36/24 brd 10.200.95.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.200.95.3/24 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::4423:9eff:fe48:c55e/64 scope link 
       valid_lft forever preferred_lft forever
[root@bdgerr00 default]# ip addr del 10.200.95.3/24 dev eth0 
[root@bdgerr00 default]# 

Any ideas?

Thanks in advance,
Flaris.

### LINKED ISSUE #194: IP-Address not switched on Hard-Shutdown
We have a three node PostgreSQL / Patroni / Etcd / Vip-Manager Cluster. When we do a planned Switchover or Shutdown, vip-manager works as expected and move the ip to the new leader. But when we kill the leader-vm (proxmox - stop) for testing purposes, vip-manager does not start the ip on the new leader even though the patroni failover works fine.

* Checking the leader with: "etcdctl get /patroni/cluster-name/leader" point to the correct server.
* Vip-Manager on the new leader still reports: IP address 192.168.1.1/24 state is false, desired false
* The issue can be solved by restarting vip-manager on the leader
* The issue also disappears when: the old leader starts again or when we wait for about 15 minutes, after this time vip-manager logs the following error and takes over the ip-address:

```
{"level":"warn","ts":"2024-01-11T16:09:30.601759+0100","logger":"etcd-client","caller":"v3@v3.5.11/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00014bc00/db1:2379","attempt":1,"error":"rpc error: code = Unavailable desc = transport is closing"}
```

* Doing a tcpdump on port 2379 reveals that no requests for /patroni/cluster-name/leader happens when we have this issue

ETCD: 3.5.11 using APIv3
VIP-Manager: 2.2 (same behaviour with 2.1)

config:

```
interval: 1000 
trigger-key: "/patroni/cluster-name/leader"
trigger-value: "db1"
ip: 192.168.1.1
netmask: 24
interface: ens18
hosting-type: basic

dcs-type: etcd
dcs-endpoints:
  - http://db1:2379
  - http://db2:2379
  - http://db3:2379

retry-num: 3
retry-after: 250
```

### PR DESCRIPTION
**Pull request by dreamingdeer**
fix etcd leader checker timeout 15 min -> 10 sec. Add verbose for get kv from etcd process
closes #194 
closes #179

### CODE REVIEW

**Comment by pashagolub** [comment]
Thanks for pointing this out! Where exactly do you see 15min timeout? Following the link you mentioned there is only one mention about 5min for gRPC. Am I missing something?

Thanks

File: main.go [hunk 1]
```diff
@@ -96,6 +96,7 @@ func main() {
 			log.Fatalf("Leader checker returned the following error: %s", err)
 		}
 		wg.Done()
+		panic("Leader checker process fail")
```
Comment (pashagolub) [inline main.go:99]: Why would we need this?

**Comment by pashagolub** [comment]
> `The only thing found - just 2 lines in log of 1 server for 15 minutes...`

Oh, I see... Thanks

File: main.go (hunk 1 above)
Comment (pashagolub) [reply main.go:99]: Process might receive signal to stop. For example, from context or from user. In this way it should exit gracefully without panic

Comment (pashagolub) [reply main.go:99]: We already have check for error and `log.Fatalf()` exactly for that case, no?
